spring:
  datasource:
    username: admin
    url: jdbc:h2:file:./db/bookdb
    driverClassName: org.h2.Driver
    password: password
  h2:
    console:
      enabled: 'true'
      path: /db-console
  #jpa = hibernate (sql생성)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8081'
